### ISSUE TITLE
application question

### ISSUE THREAD

**Issue by jschoch** [tedyapo/arduino-MLX90393#29]
Wondering in general how you go from these x,y,z numbers to a position for a diametricaly opposed magnet.  The x, and y numbers appear to roll over when turning.  Kinda hard to test since my pins on  my breakout are magnetic :(  Any help appreciated.

**Comment by tedyapo** [comment]
Check any SMT capacitors, too.  Their terminals are often magnetic.

I have never considered using this part for its seemingly intended purpose, just for measuring fields...but now you got me thinking.

If you work for a big company, get applications information from Melexis.  They might talk to you.

First, you're only reading three values from the part, so you can only determine three degrees of freedom.  You could conceivably determine any three of the six degrees of freedom (position + orientation), as long as your parts are constrained to move in only three.  You mention turning and position, so maybe you are trying to determine too many variables: you only get three.  A picture of your setup would help.

What do you want to determine?  If you just want one dimension of position, it's easy.  See [this page on hackaday.io](https://hackaday.io/project/11865-3d-magnetic-field-scanner/log/40338-mlx90393-saturation-test).  I was testing for saturation, but you can see from the plot how you could go from field strength in the z-axis to distance.  You'll need to calibrate the distance, because the field strength is not linear with distance (it has an inverse power relationship with degree between 2 and 3).

**Comment by jschoch** [comment]
I'm just worried about x and y for angular position for a diametric magnet.  I've tried 

heading_in_degrees = 180*atan2(magy,magx)/PI;

but it does not seem to work.

**Comment by tedyapo** [comment]
I tried it just now.  It seems to work OK, but could probably be improved with some work.  Have a look at [this page on hackaday.io](https://hackaday.io/project/11865-3d-magnetic-field-scanner/log/76679-rotating-magnets) and see if that helps any.  You can ask questions here or there...

**Comment by jschoch** [comment]
wow thanks!!!  I'm using a diametric magnet and from what i've read a regular magnet doesn't work optimally for this rotation application, though it does work a bit.  You can make a nice rotary encoder knob or epoxy your magnet to a motor shaft and have contactless close loop motor control!

full disclosure I was actually using a different library because I couldn't get yours to work on my esp32 which I want to use for the onboard OLED and it's BLE networking.  I have had all kinds of issues with i2c and the esp32 :(

I'll try it with a pro micro quickly to see if i get the same results using your library as the other one I was using.

the working lib for the esp32 is here which appears to use ints instead of floats and has no conversion function for the tweaks available for calibration.

https://github.com/ControlEverythingCommunity/MLX90393/blob/master/Arduino/MLX90393.ino

**Comment by tedyapo** [comment]
I used a pro micro for this test.

Please open a new issue for the library not working on an ESP32.  I have one buried somewhere in the pile that I call a desk that I can test with.

Does the ESP32 terminate the I2C lines, or do you have to do that yourself?

**Comment by jschoch** [comment]
i had assumed it did do the termination like the arduino Wire library but I'm not sure now that I took a quick look on google...  Should I test it with an external pull up?  My meter shows 3.2v on both SDA and SCL running the code I posted in the esp32 issue.

**Comment by tedyapo** [comment]
If you have them handy, try adding 4.7k (or 10k) pullups on both lines to see if that helps.
